name: build

on: push

jobs:
    mineros:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Prepare Dockerfile
                run: cp ./.github/workflows/Dockerfile .
            -   name: Docker Build
                run: docker build -t meroscrypto/mineros:latest
            -   name: Docker Login
                if: github.ref == 'refs/heads/master'
                uses: azure/docker-login@v1
                with:
                    username: merosmaintainers
                    password: ${{ secrets.DOCKER_PASSWORD }}
            -   name: Docker Publish
                if: github.ref == 'refs/heads/master'
                run: docker push meroscrypto/mineros:latest